// Code generated by Kitex v0.8.0. DO NOT EDIT.

package user

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	user "github/youminghang/search_engine/search_engine_srv/user_srv/proto/kitex_gen/user"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetUserList(ctx context.Context, Req *user.UserInfoFilter, callOptions ...callopt.Option) (r *user.UserListResponse, err error)
	GetUserById(ctx context.Context, Req *user.IdRequest, callOptions ...callopt.Option) (r *user.UserInfoResponse, err error)
	CreateUser(ctx context.Context, Req *user.CreateUserInfo, callOptions ...callopt.Option) (r *user.UserInfoResponse, err error)
	UpdateUser(ctx context.Context, Req *user.UpdateUserInfo, callOptions ...callopt.Option) (r *emptypb.Empty, err error)
	CheckPassWord(ctx context.Context, Req *user.PasswordInfo, callOptions ...callopt.Option) (r *user.CheckResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserClient struct {
	*kClient
}

func (p *kUserClient) GetUserList(ctx context.Context, Req *user.UserInfoFilter, callOptions ...callopt.Option) (r *user.UserListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserList(ctx, Req)
}

func (p *kUserClient) GetUserById(ctx context.Context, Req *user.IdRequest, callOptions ...callopt.Option) (r *user.UserInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserById(ctx, Req)
}

func (p *kUserClient) CreateUser(ctx context.Context, Req *user.CreateUserInfo, callOptions ...callopt.Option) (r *user.UserInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateUser(ctx, Req)
}

func (p *kUserClient) UpdateUser(ctx context.Context, Req *user.UpdateUserInfo, callOptions ...callopt.Option) (r *emptypb.Empty, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateUser(ctx, Req)
}

func (p *kUserClient) CheckPassWord(ctx context.Context, Req *user.PasswordInfo, callOptions ...callopt.Option) (r *user.CheckResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CheckPassWord(ctx, Req)
}
