// Code generated by Kitex v0.8.0. DO NOT EDIT.

package user

import (
	server "github.com/cloudwego/kitex/server"
	user "github/youminghang/search_engine/search_engine_srv/user_srv/proto/kitex_gen/user"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler user.User, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
