// Code generated by Kitex v0.8.0. DO NOT EDIT.
package user

import (
	server "github.com/cloudwego/kitex/server"
	user "github/youminghang/search_engine/search_engine_srv/user_srv/proto/kitex_gen/user"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler user.User, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
